-- Drop/Delete objects
-- Drop SCD triggers
DROP TRIGGER TEST.FBS_FOOTBALL_DIM_T1;
DROP TRIGGER TEST.FBS_FOOTBALL_DIM_T2;
DROP TRIGGER TEST.FBS_FOOTBALL_DIM_T3;
DROP TRIGGER TEST.FBS_FOOTBALL_DIM_T4;
ALTER TABLE TEST.FBS_FOOTBALL_DIM DROP CONSTRAINT FBS_FOOTBALL_DIM_PK;
DROP VIEW TEST.FBS_FOOTBALL_SCD_V;
DROP VIEW TEST.FBS_FOOTBALL_DIM_V;
DROP TABLE TEST.FBS_FOOTBALL_DIM;
DROP TABLESPACE TS_FBS_FOOTBALL;
COMMIT;

CREATE TABLESPACE TS_FBS_FOOTBALL MANAGED BY AUTOMATIC STORAGE;

-- Create EDS table
CREATE TABLE TEST.FBS_FOOTBALL_DIM (
      FBS_ID                   INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER )
  ,   CONF_CD                  CHAR(3) NOT NULL
  ,   DIVISION_CD              VARCHAR(10) NOT NULL
  ,   TEAM_CD                  CHAR(4) NOT NULL
  ,   INSTITUTION_NM           VARCHAR(128)
  ,   NICKNAME                 VARCHAR(128)
  ,   LOCATION_NM              VARCHAR(128)
  ,   FOUNDED_YR               INTEGER
  ,   JOINED_DT                DATE
  ,   ENROLLMENT_CT            INTEGER
  ,   ENDOWMENT_AMT            DOUBLE
  ,   AUDIT_TMS                TIMESTAMP
  ,   ROW_STATUS_CD            CHAR(1) NOT NULL DEFAULT 'I'
  ,   VERSION_NUM              INTEGER NOT NULL DEFAULT 1
  ,   EFF_TMS                  TIMESTAMP NOT NULL
  ,   EXPIR_TMS                TIMESTAMP NOT NULL
  )
  IN TS_FBS_FOOTBALL
  DATA CAPTURE NONE 
  COMPRESS NO;

--Alter table to add primary key for Surrogate Id
ALTER TABLE TEST.FBS_FOOTBALL_DIM ADD CONSTRAINT FBS_FOOTBALL_DIM_PK PRIMARY KEY (FBS_ID);

--Create UNIQUE INDEX based on the natural key and SCD attributes
CREATE UNIQUE INDEX TEST.FBS_FOOTBALL_DIM_UX1 
    ON TEST.FBS_FOOTBALL_DIM (
      CONF_CD  ASC
    , DIVISION_CD  ASC
    , TEAM_CD  ASC
    , EFF_TMS
    , EXPIR_TMS
    )
    MINPCTUSED 0
    DISALLOW REVERSE SCANS
    PAGE SPLIT SYMMETRIC
    COLLECT SAMPLED DETAILED STATISTICS
    COMPRESS NO;

--Add comments to the table
COMMENT ON TABLE TEST.FBS_FOOTBALL_DIM IS 'The NCAA Division I Football Bowl Subdivision (FBS), formerly known as Division I-A, is the top level of college football in the United States. As of 2020, there are 10 conferences and 130 schools in FBS.';

--Add comments to the columns
COMMENT ON COLUMN TEST.FBS_FOOTBALL_DIM.FBS_ID IS 'Surrogate key for TEST.FBS_FOOTBALL_DIM.';
COMMENT ON COLUMN TEST.FBS_FOOTBALL_DIM.CONF_CD IS '';
COMMENT ON COLUMN TEST.FBS_FOOTBALL_DIM.DIVISION_CD IS '';
COMMENT ON COLUMN TEST.FBS_FOOTBALL_DIM.TEAM_CD IS '';
COMMENT ON COLUMN TEST.FBS_FOOTBALL_DIM.INSTITUTION_NM IS '';
COMMENT ON COLUMN TEST.FBS_FOOTBALL_DIM.NICKNAME IS '';
COMMENT ON COLUMN TEST.FBS_FOOTBALL_DIM.LOCATION_NM IS '';
COMMENT ON COLUMN TEST.FBS_FOOTBALL_DIM.FOUNDED_YR IS '';
COMMENT ON COLUMN TEST.FBS_FOOTBALL_DIM.JOINED_DT IS '';
COMMENT ON COLUMN TEST.FBS_FOOTBALL_DIM.ENROLLMENT_CT IS '';
COMMENT ON COLUMN TEST.FBS_FOOTBALL_DIM.ENDOWMENT_AMT IS '';
COMMENT ON COLUMN TEST.FBS_FOOTBALL_DIM.AUDIT_TMS IS '';
COMMENT ON COLUMN TEST.FBS_FOOTBALL_DIM.ROW_STATUS_CD IS 'Row Status code. ''I'' - Insert, ''U'' - Update, ''D'' - Delete.';
COMMENT ON COLUMN TEST.FBS_FOOTBALL_DIM.VERSION_NUM IS 'Version number of the record''s state.';
COMMENT ON COLUMN TEST.FBS_FOOTBALL_DIM.EFF_TMS IS 'Timestamp indicating when the particular record became effective within the slow changing dimension. Note that each record of a SCD represents a ''state'' of the object/data.';
COMMENT ON COLUMN TEST.FBS_FOOTBALL_DIM.EXPIR_TMS IS 'Timestamp indicating when the particular record has expired (is no longer in effect) within the slow changing dimension.. 9999-12-31-23.59.59.999999 represents the current state of the record.';

--Views
CREATE VIEW TEST.FBS_FOOTBALL_DIM_V
AS
SELECT FBS_ID
     , CONF_CD
     , DIVISION_CD
     , TEAM_CD
     , INSTITUTION_NM
     , NICKNAME
     , LOCATION_NM
     , FOUNDED_YR
     , JOINED_DT
     , ENROLLMENT_CT
     , ENDOWMENT_AMT
     , AUDIT_TMS
FROM   TEST.FBS_FOOTBALL_DIM
WHERE  EXPIR_TMS = '9999-12-31-23.59.59.999999';

CREATE VIEW TEST.FBS_FOOTBALL_SCD_V
AS
SELECT *
FROM   TEST.FBS_FOOTBALL_DIM;


--Create Triggers to manage SCD
--T1 Set Effective and Expiration Timestamps on new/inserted records
CREATE TRIGGER TEST.FBS_FOOTBALL_DIM_T1
    BEFORE INSERT ON TEST.FBS_FOOTBALL_DIM
    REFERENCING  NEW AS NEWVAL
    FOR EACH ROW
SET EFF_TMS       = CURRENT TIMESTAMP
  ,  EXPIR_TMS     = '9999-12-31-23.59.59.999999'
  ,  ROW_STATUS_CD = 'I';

--T2 Expire previous record for the natural key (EXPIR_TMS = N.EFF_TMS - 1 MICROSECOND)
CREATE TRIGGER TEST.FBS_FOOTBALL_DIM_T2
    AFTER INSERT ON TEST.FBS_FOOTBALL_DIM
    REFERENCING  NEW AS N
    FOR EACH ROW
UPDATE TEST.FBS_FOOTBALL_DIM
  SET EXPIR_TMS     = N.EFF_TMS - 1 MICROSECOND 
    , ROW_STATUS_CD = 'H'
WHERE CONF_CD = N.CONF_CD
  AND DIVISION_CD = N.DIVISION_CD
  AND TEAM_CD = N.TEAM_CD
--  AND VERSION_NUM   = N.VERSION_NUM-1 
  AND EXPIR_TMS     = '9999-12-31-23.59.59.999999'
  AND EFF_TMS       < N.EFF_TMS;

--T3 Change DELETE transaction to expire previous record for the natural key.
CREATE TRIGGER TEST.FBS_FOOTBALL_DIM_T3
    INSTEAD OF DELETE ON TEST.FBS_FOOTBALL_DIM_V
    REFERENCING  OLD AS O
    FOR EACH ROW
UPDATE TEST.FBS_FOOTBALL_DIM
  SET EXPIR_TMS     = CURRENT TIMESTAMP
    , ROW_STATUS_CD = 'D'
WHERE CONF_CD = O.CONF_CD
  AND DIVISION_CD = O.DIVISION_CD
  AND TEAM_CD = O.TEAM_CD
  AND EXPIR_TMS     = '9999-12-31-23.59.59.999999';

--T4 Change UPDATE transaction to insert a new record.
-- The insert will invoke T1 to set the effective and expiration timestamp and
-- T2 to expire previous record for the natural key.
CREATE TRIGGER TEST.FBS_FOOTBALL_DIM_T4
    INSTEAD OF UPDATE ON TEST.FBS_FOOTBALL_DIM_V
    REFERENCING  NEW AS N
    FOR EACH ROW
INSERT INTO TEST.FBS_FOOTBALL_DIM
 (CONF_CD, DIVISION_CD, TEAM_CD, INSTITUTION_NM, NICKNAME, LOCATION_NM, FOUNDED_YR, JOINED_DT, ENROLLMENT_CT, ENDOWMENT_AMT, AUDIT_TMS)
VALUES
 (N.CONF_CD, N.DIVISION_CD, N.TEAM_CD, N.INSTITUTION_NM, N.NICKNAME, N.LOCATION_NM, N.FOUNDED_YR, N.JOINED_DT, N.ENROLLMENT_CT, N.ENDOWMENT_AMT, N.AUDIT_TMS);
 
grant select on table TEST.FBS_FOOTBALL_DIM_V to role read_access_dev;
grant select on table TEST.FBS_FOOTBALL_SCD_V to role read_access_dev;