# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: WFM Documentation
email: ponessa@us.ibm.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#baseurl: ""
baseurl: "/IBM-Consulting-WFM/wfm-dmf-ga" # the subpath of your site, e.g. /blog
url: "https://ms-spring-server.dal1a.ciocloud.nonprod.intranet.ibm.com" # the base hostname & protocol for your site, e.g. http://example.com
contact_reference: "https://ibm.enterprise.slack.com/user/@W52QZ3BJ8"
twitter_username: "@PonessaSteven"
github_username:  ponessa@us.ibm.com
organization: WFM
documentation_landing_page: "/IBM-Consulting-WFM/wfm-dmf-ga"
footer_links: [
  {"title": "Terms", "url": "https://w3.ibm.com/#/info_terms_of_use"},
  {"title": "Privacy", "url": "https://w3.ibm.com/w3-privacy-notice"},
  {"title": "WFM Home", "url": "https://w3.ibm.com/w3publisher/ibm-services-workforce-management"}
]

max_abstract_length: 240

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: en/:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true